name: CI + CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  # ----------------------
  # Build Job
  # ----------------------
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Compile
        run: echo "Building the application..."

  # ----------------------
  # Deploy to Development
  # ----------------------
  DeployDev:
    name: Deploy to Development
    needs: [Build]
    runs-on: ubuntu-latest
    environment: 
      name: Development
      url: 'http://dev.myapp.com'
    steps:
      - name: Deploy
        run: echo "Deploying to Development environment..."

  # ----------------------
  # Deploy to QA
  # ----------------------
  DeployQA:
    name: Deploy to QA
    needs: [DeployDev]
    runs-on: ubuntu-latest
    environment:
      name: QA
      url: 'http://qa.myapp.com'
    steps:
      - name: Deploy
        run: echo "Deploying to QA environment..."

  # ----------------------
  # Deploy to Preview
  # ----------------------
  DeployPreview:
    name: Deploy to Preview
    needs: [DeployQA]
    runs-on: ubuntu-latest
    environment:
      name: Preview
      url: 'http://preview.myapp.com'
    steps:
      - name: Deploy
        run: echo "Deploying to Preview environment..."
