name: Non-Prod Envs Syncing to S3

on:
  push:
    branches:
      - Dev-1
      - Qa
      - Staging
      - Int

jobs:
  sync-envs:
    name: Syncing to S3 (${{ github.ref_name }})
    runs-on: ubuntu-latest
    environment: TTSP

    steps:
      - name: Get branch name
        id: extract_branch
        run: |
          BRANCH_NAME=${GITHUB_REF##*/}
      
          # Lowercase version
          LOWER_BRANCH=${BRANCH_NAME,,}
      
          # Print both to the logs
          echo "Original branch name: $BRANCH_NAME"
          echo "Lowercase branch name: $LOWER_BRANCH"
      
          # Save lowercase version as a step output
          echo "branch_name=${LOWER_BRANCH}" >> $GITHUB_OUTPUT


