name: Dev Envs Syncing to S3

on:
  push:
    branches:
      - Dev
      - Staging
      - Int

jobs:
  sync-envs:
    name: Syncing to S3
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
